### ISSUE TITLE
asbtools not available

### ISSUE THREAD

**Issue by skofield05** [abresler/bertopic#1]
Hey there,

I get the following error when I try to install via `devtools::install_github("abresler/bertopic")`:

`ERROR: dependency 'asbtools' is not available for package 'bertopic'`

When I do `remotes::install_github("abresler/asbtools")` or `devtools::install_github("abresler/asbtools")` I get the following:

```
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found
```

**Comment by abresler** [comment]
Try it now

**Comment by skofield05** [comment]
Thank you! Now it worked

**Comment by andolph123** [comment]
Hi

As per above, I can't access asbtools using either remotes::install_github("abresler/asbtools") or devtools::install_github("abresler/asbtools") - I am getting the same error as skofield05 above even though this has apparently been fixed on Jan 10 - please advise

**Comment by tpetric7** [comment]
You can use BERTopic in R with other packages: "text" (https://github.com/OscarKjell/text) and "bertopicr" (https://github.com/tpetric7/bertopicr).
