### ISSUE TITLE
Failed to update package

### ISSUE THREAD

**Issue by oyvindbso** [abresler/bertopic#5]
Hi, 
Thank you for making the package! I tried to update the package today but I got an error. The installation failed in both R and RStudio. I'm on windows 10 with R 4.2.1 and Rstudio 2023.03.0 Build 386.

The installation returned the following error:

` 
   checking for file 'C:\Users\...\AppData\Local\Temp\RtmpykOT7U\remotes452cc1059c8\abresler-bertopic-15a1932/DESCRIPTION' ...
✔  checking for file 'C:\Users\...\AppData\Local\Temp\RtmpykOT7U\remotes452cc1059c8\abresler-bertopic-15a1932/DESCRIPTION'
─  preparing 'bertopic': (779ms)
   checking DESCRIPTION meta-information ...  
   checking DESCRIPTION meta-information ... 
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'bertopic_0.1.1.tar.gz'

Installing package into ‘C:/Users/.../AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'bertopic' ...
** using staged installation
** R
Error in parse(outFile) : 
  The pipe operator requires a function call as RHS
ERROR: unable to collate and parse R files for package 'bertopic'
* removing 'C:/Users/.../AppData/Local/R/win-library/4.2/bertopic'
* restoring previous 'C:/Users/.../AppData/Local/R/win-library/4.2/bertopic'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/.../AppData/Local/Temp/RtmpykOT7U/file452c12ed342c/bertopic_0.1.1.tar.gz’ had non-zero exit status

`

**Comment by abresler** [comment]
I have not checked compatability with windows machines.

My advice would be to use reticulate with the BERTopic module
